---
title: "MATH 216 Homework 2 Shiny App"
author: "Katherine Hobbs"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}

inputPanel(
  # Genre
  radioButtons("Genre", label = "Choose a Genre:", c("Comedies"= "Comedies", "Other" = "Other"))
)

renderPlot({

  # Generate Plots

  movies_input <- movies %>% 
    mutate(Genre = ifelse(Comedy == 1, "Comedies", "Other")) %>% 
    filter(!is.na(budget)) %>% 
    filter(Genre == input$Genre)
  
  ggplot(data=movies_input, aes(x=budget, y=rating)) + 
    geom_point() +
    geom_smooth() +
    xlab("Budget") +
    ylab("Rating") +
    ggtitle("Ratings vs. Budget for Comedies and Non-Comedies")
  

})
```
